
#ifndef MEGO_COMMON_H_INCLUDED
#define MEGO_COMMON_H_INCLUDED

#ifndef MGOPT__USE_MEMESTR
#define MGOPT__USE_MEMESTR (1)
#endif

#ifndef MGOPT__SYM_VIS_HIDDEN_ENABLED
#define MGOPT__SYM_VIS_HIDDEN_ENABLED (0)
#endif

#endif // !MEGO_COMMON_H_INCLUDED
