
#ifndef MEGO_PREDEF_SYMBOL_COMPILER_GCC_FORMAT_H_INCLUDED
#define MEGO_PREDEF_SYMBOL_COMPILER_GCC_FORMAT_H_INCLUDED

#include "mego/predef/compiler/gcc.h"

#if MEGO_COMP__GCC__AVAILABLE

#ifndef MEGO_SYMBOL__GCC_ATTRIBUTE_FORMAT
#define MEGO_SYMBOL__GCC_ATTRIBUTE_FORMAT(ARCHETYPE, STRING_INDEX, FIRST_TO_CHECK) \
    __attribute__((format(ARCHETYPE, STRING_INDEX, FIRST_TO_CHECK)))
#endif

#endif

#ifndef MEGO_SYMBOL__GCC_ATTRIBUTE_FORMAT
#define MEGO_SYMBOL__GCC_ATTRIBUTE_FORMAT(ARCHETYPE, STRING_INDEX, FIRST_TO_CHECK) 
#endif

#ifndef MG_SYM__GCC_ATTR_FMT
#define MG_SYM__GCC_ATTR_FMT MEGO_SYMBOL__GCC_ATTRIBUTE_FORMAT
#endif

#endif // !MEGO_PREDEF_SYMBOL_COMPILER_GCC_FORMAT_H_INCLUDED
