
#ifndef MEMEPP_COMMON_HPP_INCLUDED
#define MEMEPP_COMMON_HPP_INCLUDED

#include <mego/predef/helper_macros.h>

#define MMPP_VER__MAJOR 0
#define MMPP_VER__MINOR 0
#define MMPP_VER__PATCH 4

#define MMPP_NAMESPACE_DO_CONCAT_IMPL(MAJOR, MINOR, PATCH) \
    v ## MAJOR ## _ ## MINOR ## _ ## PATCH

#define MMPP_NAMESPACE_DO_CONCAT(MAJOR, MINOR, PATCH) \
    MMPP_NAMESPACE_DO_CONCAT_IMPL(MAJOR, MINOR, PATCH)

#define MMPP_NAMESPACE \
    MMPP_NAMESPACE_DO_CONCAT(MMPP_VER__MAJOR, MMPP_VER__MINOR, MMPP_VER__PATCH)

#endif // !MEMEPP_COMMON_HPP_INCLUDED
