
#ifndef MEME_PREDEF_MACRO_OPTION_H_INCLUDED
#define MEME_PREDEF_MACRO_OPTION_H_INCLUDED

#ifndef MMOPT__SIMD_DISABLED
#define MMOPT__SIMD_DISABLED (0)
#endif // !MMOPT__SIMD_DISABLED

#endif // !MEME_PREDEF_MACRO_OPTION_H_INCLUDED
