
#ifndef MEME_UTF_U8RUNE_FWD_H_INCLUDED
#define MEME_UTF_U8RUNE_FWD_H_INCLUDED

#include <meme/string_fwd.h>

MEME_EXTERN_C_SCOPE_START

MEME_EXTERN_C_SCOPE_ENDED

#endif // !MEME_UTF_U8RUNE_FWD_H_INCLUDED
