
#ifndef MEMEPP_PREDEF_MACRO_OPTION_HPP_INCLUDED
#define MEMEPP_PREDEF_MACRO_OPTION_HPP_INCLUDED

#ifndef MEMEPP_OPTION__EXCEPTION_DISABLED 
#define MEMEPP_OPTION__EXCEPTION_DISABLED (0)
#endif 

#endif // !MEMEPP_PREDEF_MACRO_OPTION_HPP_INCLUDED
